export const cartStyles: any = {
  emptyWithAction: { flex: 1, justifyContent: "center", paddingHorizontal: 18 },
  defaultLabel: { color: "#007C91", fontSize: 10, fontWeight: "900" as const, backgroundColor: "#E8F7F8", paddingHorizontal: 6, paddingVertical: 3, borderRadius: 6 },
  deliveryOptions: { flexDirection: "row" as const, gap: 7 },
  deliveryOption: { flex: 1, minHeight: 88, padding: 8, alignItems: "center" as const, justifyContent: "center" as const, borderColor: "#DCE5EB", borderWidth: 1, borderRadius: 13, backgroundColor: "#FFFFFF" },
  deliveryOptionActive: { borderColor: "#007C91", backgroundColor: "#E8F7F8", borderWidth: 2 },
  deliveryIcon: { fontSize: 20 },
  deliveryLabel: { color: "#1D2939", fontSize: 12, fontWeight: "900" as const, marginTop: 4 },
  deliveryLabelActive: { color: "#007C91" },
  deliveryDesc: { color: "#667085", fontSize: 9, lineHeight: 13, textAlign: "center" as const, marginTop: 3 },
  dateSelect: { minHeight: 46, paddingHorizontal: 12, justifyContent: "center" as const, borderColor: "#DCE5EB", borderWidth: 1, borderRadius: 11, backgroundColor: "#FFFFFF" },
  dateSelectDisabled: { backgroundColor: "#EAECF0", opacity: 0.72 },
  dateSelectText: { color: "#667085", fontSize: 12, fontWeight: "700" as const },
  deliverySummary: { color: "#007C91", fontSize: 11, fontWeight: "800" as const, marginTop: 3 },
  modalBackdrop: { flex: 1, justifyContent: "center" as const, alignItems: "center" as const, padding: 24, backgroundColor: "#10182899" },
  confirmModal: { width: "100%" as const, maxWidth: 360, padding: 22, gap: 12, borderRadius: 20, backgroundColor: "#FFFFFF", shadowColor: "#102A43", shadowOpacity: 0.2, shadowRadius: 18, shadowOffset: { width: 0, height: 8 }, elevation: 8 },
  modalClose: { position: "absolute" as const, top: 9, right: 9, zIndex: 2, width: 34, height: 34, alignItems: "center" as const, justifyContent: "center" as const, borderRadius: 17, backgroundColor: "#F4F7F9" },
  modalIcon: { fontSize: 34, textAlign: "center" as const },
  modalTitle: { color: "#102A43", fontSize: 19, fontWeight: "900" as const, textAlign: "center" as const },
  modalCopy: { color: "#667085", fontSize: 13, lineHeight: 19, textAlign: "center" as const },
  textButton: { color: "#667085", fontSize: 13, fontWeight: "800" as const, textAlign: "center" as const, padding: 9 },
  cartFeedbackInfo: { padding: 12, gap: 8, borderRadius: 12, backgroundColor: "#F4F7F9", borderColor: "#DCE5EB", borderWidth: 1 },
  modalActionRow: { flexDirection: "row" as const, gap: 8 },
  orderNote: { marginTop: 8, padding: 10, borderRadius: 10, backgroundColor: "#E8F7F8" },
  orderNoteLabel: { color: "#007C91", fontSize: 11, fontWeight: "900" as const },
  orderNoteText: { color: "#344054", fontSize: 12, lineHeight: 18, marginTop: 4 },
};
